[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'shim/Mock']
solc_version = "0.8.17"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "solmate/=lib/solmate/src/",
  "bytes-utils/=lib/solidity-bytes-utils/contracts/",
  "filecoin-solidity/=lib/filecoin-solidity/contracts/v0.8/",
  "solidity-cborutils/=lib/solidity-cborutils/",
  "@ensdomains/buffer/=lib/buffer/",
  "src/=src/",
  "deploy/=deploy/",
  "shim/=shim/Mock/"
]

[profile.fevm]
src = 'src'
out = 'out-fevm'
libs = ['lib', 'shim/FEVM']
solc_version = "0.8.17"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "solmate/=lib/solmate/src/",
  "bytes-utils/=lib/solidity-bytes-utils/contracts/",
  "filecoin-solidity/=lib/filecoin-solidity/contracts/v0.8/",
  "solidity-cborutils/=lib/solidity-cborutils/",
  "@ensdomains/buffer/=lib/buffer/",
  "src/=src/",
  "deploy/=deploy/",
  "shim/=shim/FEVM/",
  "fevmate/=lib/fevmate/contracts/",
  "glifmate/=lib/glifmate/src/",
  "@zondax/solidity-bignumber/=lib/filecoin-solidity/lib/solidity-bignumber/"
]
optimizer_details.yul = false

[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
